# this config file is for installer.71m.us

name: ss-server
image: ubuntu-14-04-x64
min_size: 512mb
config:
  packages:
    - git
    - ansible
  runcmd:
    - mkdir -p /opt/ && git clone https://github.com/lexrus/ios-dev-playbook.git /opt/idp && cd /opt/idp && ansible-playbook 022_shadowsocks.yml -i ansible_localhost.ini -e "port=5333 password=ilovelex method=aes-256-cfb" --skip-tags="hostname build-essential editor git mosh ranger imagemagick exim4"
