# this config file is for installer.71m.us

name: ss-server
image: ubuntu-14-04-x64
min_size: 512mb
config:
  packages:
    - git
    - ansible
  runcmd:
    - mkdir -p /opt/ && git clone https://github.com/lexrus/vpn-deploy-playbook.git /opt/vdp && cd /opt/vdp && ansible-playbook proxy-backend.yml -i ansible_hosts.local -e "shadowsocks_provider=python shadowsocks_change_tcp_congestion_control=true enable_udp=false port=5333 password=ilovelex method=aes-256-cfb"
